# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # http://stackoverflow.com/a/8210892/1101589
    ekv_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [ekv]
        calls:
            - [pushHandler, [@ekv_handler]]
            - [pushHandler, [@ekv_handler1]]

    ekv_handler:
        class: Monolog\Handler\StreamHandler
        # 200 = INFO, see Monolog::Logger for the values of log levels
        arguments: [%kernel.logs_dir%/%kernel.environment%.ekv.log, 200]

    ekv_handler1:
        class: Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/%kernel.environment%.ekv-warn.log, 300]

    # registration form
    app_user.registration.form.type:
        class: AppUserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ekv_user_registration }

    # listener for registration
    app_user.reg_init:
        class: AppUserBundle\EventListener\RegistrationListener
        arguments: [@ekv_logger]
        tags:
            - { name: kernel.event_subscriber }