services:
    app.admin.movie:
        class: AppBundle\Admin\MovieAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Movie" }
        arguments:
            - ~
            - AppBundle\Entity\TrMovie
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ addChild, ['@app.admin.episode']]

    app.admin.episode:
        class: AppBundle\Admin\EpisodeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Episodes" }
        arguments:
            - ~
            - AppBundle\Entity\TrEpisode
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ addChild, ['@app.admin.word']]

    app.admin.word:
        class: AppBundle\Admin\WordAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Words" }
        arguments:
            - ~
            - AppBundle\Entity\TrWord
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]